# Generated by Django 6.0.2 on 2026-02-11 08:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(db_index=True, max_length=120)),
                ("last_name", models.CharField(db_index=True, max_length=120)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("mobile", models.CharField(db_index=True, max_length=15)),
                ("role", models.CharField(db_index=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "employees",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["first_name", "last_name"], name="emp_name_idx"
                    ),
                    models.Index(fields=["-created_at"], name="emp_created_idx"),
                    models.Index(
                        django.db.models.functions.text.Lower("email"),
                        name="emp_email_lower_idx",
                    ),
                    models.Index(
                        django.db.models.functions.text.Lower("first_name"),
                        name="emp_fname_lower_idx",
                    ),
                    models.Index(
                        django.db.models.functions.text.Lower("last_name"),
                        name="emp_lname_lower_idx",
                    ),
                ],
            },
        ),
    ]
